apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespaceconfig-preupgrade
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceconfig-preupgrade
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaceconfigs/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaceconfigs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespaceconfig-preupgrade
  labels:
    {{- include "msai-aks-base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaceconfig-preupgrade
subjects:
  - name: namespaceconfig-preupgrade
    namespace: kube-system
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: namespaceconfig-preupgrade
  namespace: kube-system
spec:
  template:
    metadata:
      name: namespaceconfig-preupgrade
    spec:
      restartPolicy: Never
      serviceAccountName: namespaceconfig-preupgrade
      containers:
      - name: preupgrade
        image: "bitnami/kubectl:latest"
        command: ["/bin/bash"]
        args:
        - -c
        - |
            set -x  # print each line as evaluated
            NSCONFIG_OBJECTS=$(kubectl get namespaceconfig | grep -v NAME | awk '{ print $1 }')
            test -z "$NSCONFIG_OBJECTS" && echo "No namespaceconfig objects found..." && exit 0
            echo "Checking the Finalizer value and deletiontimestamp in the objects."
            for NSCO in $NSCONFIG_OBJECTS; do
              OBJ_DETAILS=$(kubectl get namespaceconfig $NSCO -o jsonpath='{.metadata.finalizers[0]},{.metadata.deletionTimestamp}')
              FINIALIZER_NAME=$(echo $$OBJ_DETAILS | awk -F',' '{print $1}')
              DELETION_TIMESTAMP=$(echo $OBJ_DETAILS | awk -F','  '{print $2}')
              if [ "$FINIALIZER_NAME" == "namespace-config-operator" -a "$DELETION_TIMESTAMP" != "" ]; then
                  echo  "Found old Finializer in the NamespaceConfig object and also marked for deletion. \n
                        Making the Finalizers list to empty to get the object deleted."
                  kubectl patch --type=merge namespaceconfig  $NSCO -p '{"metadata": {"finalizers": null}}'
              fi
            done
            while true; do
                NAMESPACECONFIG_CRD=$(kubectl get crd namespaceconfigs.redhatcop.redhat.io --ignore-not-found=true | grep -v NAME | awk '{ print $1 }')
                test -z "$NAMESPACECONFIG_CRD" && echo "namespaceconfigs CRD is deleted..." && exit 0
                echo "Waiting for the namespaceconfigs crd to be deleted. Sleeping 10 seconds."
                sleep 10
            done
